### ISSUE TITLE
`DKIM` support

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#389]
# Context

```
DomainKeys Identified Mail (DKIM) permits a person, role, or
organization that owns the signing domain to claim some
responsibility for a message by associating the domain with the
message. 
```

See https://datatracker.ietf.org/doc/html/rfc6376
And https://datatracker.ietf.org/doc/html/rfc8301
And https://datatracker.ietf.org/doc/html/rfc8463

## Outgoing side (sender or signer)

After editing a message, a `DKIM-Signature` can be added to the message.

* [x] add a function `dkim_sign` in the `vsl` api, adding a new signature to the message
* [x] multiple signer mechanisms should be possible (https://github.com/viridIT/vSMTP/pull/629)

## Incoming side (receiver or verifier)

On message reception, the `DKIM-Signature`s headers should be verified, and the outcome defined by the user's `vsl` logics.

* [x] add a function `dkim_verify` in the `vsl` api

## Documentation

* [x] update the dkim chapter in the book
* [ ] add a section for delegated policy

## Features

* [x] deprecated algorithm MUST be under a `--features historic`
* [x] add a minimum key size
* [x] on boot, the DNS record specified for the signature COULD be verified
* [x] support `ed25519` key and algorithm (https://github.com/viridIT/vSMTP/pull/600)

**Comment by Mathieu-Lala** [comment]
Concerning the `on boot, the DNS record specified for the signature COULD be verified`, we decided that is it not the responsibility of the MTA to ensure (or warn) the validity of the site.
You can use http://www.opendkim.org/opendkim-testkey.8.html for this purpose.
