### ISSUE TITLE
LMTP

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#53]
vSMTP might implement LMTP see rfc : https://datatracker.ietf.org/doc/html/rfc2033

* [ ] MUST implement the PIPELINING
* [ ] MUST implement the ENHANCEDSTATUSCODES
* [ ] must not be used over TCP port 25
* [ ] HELO and EHLO commands of ESMTP are replaced by the LHLO
* [ ] LMTP server MUST NOT return a Postive Completion reply code to these commands.  The 500 reply code is recommended.
* [ ] LMTP has identical semantics to the EHLO command of ESMTP
* [ ]  when there have been no successful RCPT commands in the mail transaction, the DATA command MUST fail with a 503 reply code
* [ ]  after the final ".", the server returns one reply
   for each previously successful RCPT command in the mail transaction,
   in the order that the RCPT commands were issued.  Even if there were
   multiple successful RCPT commands giving the same forward-path, there
   must be one reply for each successful RCPT command.
* [ ]  When one of these replies to the final "." is a Positive Completion
   reply, the server is accepting responsibility for delivering or
   relying the message to the corresponding recipient

**Comment by Mathieu-Lala** [comment]
It is very interesting to support LMTP but as it is incompatible with SMTP (according to the rfc) we should use a `--feature lmtp` or equivalent.
This issue will be reopened when we have a more precise idea of the implementation.

**Comment by pingiun** [comment]
LMTP would be useful as a protocol to send local mail to a MDA like [stalwart](https://stalw.art/jmap/configure/lmtp/)

**Comment by pingiun** [comment]
I opened an issue at lettre because it would be nice if vSMTP could just use lettre for it's SMTP/LMTP client stuff everywhere: https://github.com/lettre/lettre/issues/820
